cues_view:
    resource: "@CUESViewBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
cues_admin:
    resource: "@CUESAdminBundle/Controller"
    type:     annotation
    prefix:   /admin